
SOURCES:
  BLEUTRADE:
    BTG:
    ETH: 
    LTC:
  CRYPTOPIA:
    all: cryptopia
  CRYPTO-BRIDGE:
    all: bit-shares
  GDAX: 
    all: gdax
  NICEHASH:
    all:
      - https://api.nicehash.com/api?method=balance&id=$API_ID&key=$API_KEY
      - https://api.nicehash.com/api?method=stats.provider&addr=$API_WALLET
  MININGPOOLHUB:
    all: https://miningpoolhub.com/index.php?page=api&action=getuserallbalances&api_key=$API_KEY
  UNIMINING:
    GBX: https://www.unimining.net/api/walletEx?address=$API_ID
    TZC: https://www.unimining.net/api/walletEx?address=$API_ID
  SUPRNOVA:
    HUSH: https://hush.suprnova.cc/index.php?page=api&action=getuserbalance&api_key=$API_KEY&id=$API_ID,
    KMD: https://kmd.suprnova.cc/index.php?page=api&action=getuserbalance&api_key=$API_KEY&id=$API_ID,
    RVN: https://rvn.suprnova.cc/index.php?page=api&action=getuserbalance&api_key=$API_KEY&id=$API_ID,
    ZEN: https://zen.suprnova.cc/index.php?page=api&action=getuserbalance&api_key=$API_KEY&id=$API_ID
  OPEN-LEDGER:
    all: bit-shares

SCOPING:
  MINING: [ MININGPOOLHUB, NICEHASH, SUPRNOVA, UNIMINING ]
  EXCHANGING: [ BLEUTRADE, CRYPTOPIA, CRYPTO-BRIDGE, OPEN-LEDGER ]
  BANKING: [ GDAX ]

COMMON_TO_SYMBOL:
  bitcoin-private: BTCP
  ethereum-classic: ETC
  bitcoin-gold: BTG
  ethereum: ETH
  expanse: EXP
  monero: XMR
  zcash: ZEC
  musicoin: MUSIC
  zclassic: ZCL
  zencash: ZEN
