
SOURCES:
  ANORAK:
    ETH(coinbase): https://etc.anorak.tech/api/accounts/$API_ID
    ETC(binance): https://etc.anorak.tech/api/accounts/$API_ID
  AIKAPOOL:
    GBX: MPOS:https://aikapool.com/gbx
  BINANCE:
    ETC: https://api.binance.com
  BLEUTRADE:
    BTG:
    ETH:
    LTC:
  CRYPTOPIA:
    all: cryptopia
  CRYPTOBRIDGE:
    all: bit-shares
  GDAX: 
    all: gdax
  NICEHASH:
    BTC: https://api.nicehash.com/api?method=balance&id=$API_ID&key=$API_KEY
  MININGPOOLHUB:
    all: https://miningpoolhub.com/index.php?page=api&action=getuserallbalances&api_key=$API_KEY
  SUPRNOVA:
    HUSH: MPOS:https://hush.suprnova.cc
    KMD: MPOS:https://kmd.suprnova.cc
    RVN: MPOS:https://rvn.suprnova.cc
    STAK: MPOS:https://stak.suprnova.cc
    ZEN: MPOS:https://zen.suprnova.cc
  OPEN-LEDGER:
    all: bit-shares
  UNIMINING:
    GBX: yiimp:https://www.unimining.net
    TZC: yiimp:https://www.unimining.net
    XMN: yiimp:https://www.unimining.net
  ZPOOL:
    GBX: yiimp:https://www.zpool.ca

SCOPING:
  MINING: [ ANORAK, AIKAPOOL, MININGPOOLHUB, NICEHASH, SUPRNOVA, UNIMINING ]
  EXCHANGING: [ BLEUTRADE, CRYPTOPIA, CRYPTOBRIDGE, OPEN-LEDGER ]
  BANKING: [ GDAX ]

COMMON_TO_SYMBOL:
  bitcoin-private: BTCP
  ethereum-classic: ETC
  bitcoin-gold: BTG
  ethereum: ETH
  expanse: EXP
  monero: XMR
  zcash: ZEC
  musicoin: MUSIC
  zclassic: ZCL
  zencash: ZEN

SYMBOL_TO_COMMON:
  XMN: MTN

OWN_READER:
  bit-shares: bit-shares
  cryptopia: cryptopia
  gdax: gdax
  UNIMINING: yiimp
  yiimp: yiimp
  MPOS: MPOS
