#!/bin/bash

##### STOP - This is an ASIC miner, not much use to us. Works only on a laarge number of ASIC devices.

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

apt-get -y install build-essential autoconf automake libtool pkg-config libcurl3-dev libudev-dev libcurl4-openssl-dev lrzip

pushd /opt

wget http://ck.kolivas.org/apps/cgminer/4.9/cgminer-4.9.2.tar.lrz || exit 1
lrunzip cgminer-4.9.2.tar.lrz
tar -xf cgminer-4.9.2.tar
cd cgminer-4.9.2
  CFLAGS="-O2 -Wall -march=native" ./configure
  make && make install
