#!/bin/bash

### See: https://github.com/sgminer-dev/sgminer/blob/master/doc/configuration.md
### Ref: https://vergecurrency.com/mining/

apt-get -y install libcurl4-openssl-dev pkg-config libtool libncurses5-dev
pushd /opt

git clone https://github.com/sgminer-dev/sgminer.git
cd sgminer

git submodule init
git submodule update
autoreconf -i
CFLAGS="-O2 -Wall -march=native -std=gnu99" ./configure --without-curses
## There is one coding error; just change the 'TRUE' to 'true' in sgminer.c:811
sed -i.bak 's/pool->backup = TRUE;/pool->backup = true;/' sgminer.c
make
make install

echo 'export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH' > /etc/profile.d/sgminer.sh

sgminer --version
#> sgminer 5.6.1-nicehash

# sgminer -o stratum+tcp://equihash.usa.nicehash.com:3357 -u 346u4oMvACtZQK9RASzcgYoZwX4JaAd3Pi.sgminer -p p=0.5;d=1024;f0=1;c0=0.5

popd
