#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

### See: https://github.com/sgminer-dev/sgminer/blob/master/doc/configuration.md

pushd /opt

apt-get -y install libcurl4-openssl-dev pkg-config libtool libncurses5-dev

git clone https://github.com/aceneun/sgminer-gm-x16r.git
cd sgminer-gm-x16r

git submodule init
git submodule update
autoreconf -i
CFLAGS="-O2 -Wall -march=native -std=gnu99" ./configure --without-curses
make
[ -f /usr/local/bin/sgminer ] && mv /usr/local/bin/sgminer /usr/local/bin/sgminer-save
make install
mv /usr/local/bin/sgminer /usr/local/bin/sgminer-gm-x16r
[ -f /usr/local/bin/sgminer-save ] && mv /usr/local/bin/sgminer-save /usr/local/bin/sgminer

cat >> /etc/profile.d/sgminer-gm-x16r.sh << SGMINER_SH
export INSTALL_SGMINER_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
SGMINER_SH
source /etc/profile.d/sgminer.sh

sgminer --version
#> sgminer 5.6.1-nicehash

popd
