#!/bin/bash

### Ref: http://www.nvidia.com/Download/index.aspx

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit $?
	fi

pushd /opt

[ -n "$INSTALL_NVIDIA_DONE" ] && echo "Nvidia drivers and support already installed $INSTALL_NVIDIA_DONE." && echo "To restart over from scratch, 'rm /etc/profile.d/nvidia.sh', logout, and retry." && exit 0

NVIDIA_VERSION=${1:-390.59}
NVIDIA_VER_PTC=(${NVIDIA_VERSION//./ })
NVIDIA_VER=${NVIDIA_VER_PTC[0]}
NVIDIA_SUB=${NVIDIA_VER_PTC[1]}

################################################################################
### Phase 0: Setup autostart ###################################################
[ -f /etc/profile.d/nvidia.sh ] && source /etc/profile.d/nvidia.sh
if [ -z "$INSTALL_NVIDIA" ]; then

cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA_STARTED=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_SH

fi
source /etc/profile.d/nvidia.sh

################################################################################
### Phase 1: Remove Nouveau ####################################################
if [ -z "$NVIDIA_NOUVEAU_REMOVED" ]; then
  echo "Removing and disabling nouveau"
  
### Ref: https://github.com/pearsonlab/pearsonlab.github.io/wiki/Things-to-know-when-installing-NVIDIA-drivers
  apt-get -y remove --purge nvidia* nouveau* && apt-get -y autoremove
  cat > /etc/modprobe.d/disable-nouveau.conf << DISABLE_NOUVEAU
blacklist nouveau
options nouveau modeset=0
blacklist lbm-nouveau
blacklist nvidia-173
blacklist nvidia-96
blacklist nvidia-current
blacklist nvidia-173-updates
blacklist nvidia-96-updates
alias nvidia nvidia_current_updates
alias nouveau off
alias lbm-nouveau off
DISABLE_NOUVEAU

  cat > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf << BLACKLIST_NOUVEAU
blacklist nouveau
options nouveau modeset=0
BLACKLIST_NOUVEAU

### TODO: Why update-initramfs if 'remove --purge' didn't do anything?
###    0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.
###    update-initramfs: Generating /boot/initrd.img-4.13.0-36-generic
  update-initramfs -u

  echo "NVIDIA_NOUVEAU_REMOVED="`date --utc +%Y-%m-%dT%H-%M-%SZ` >> /etc/profile.d/nvidia.sh
  echo "Nouveau has been removed and disabled."
  echo "After this reboot, install-nvidia will proceed with installing Nvidia drivers."

  echo "Hit ctrl-C to abort the reboot."
  sleep 10
  reboot

fi


################################################################################
### Phase 2: Install Nvidia drivers ############################################
################################################################################
if [ -z "$NVIDIA_DRIVERS_INSTALLED" ]; then
  cd /opt/Downloads/
if [ -n "$USE_RUN_METHOD" ]; then # USE_RUN_METHOD
  [ -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
  wget https://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VER}.${NVIDIA_PATCH}/NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
  [ ! -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && echo "Nvidia Drivers download failed!" && exit 1
  ### Question: When will we ever need X server?
  ### Answer: nvidia-settings is too stupid to talk directly to its own GPUs and has to use X-server to do that for it.
  service lightdm stop
  sh NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run --no-questions --disable-nouveau --ui=none --run-nvidia-xconfig
  NVIDIA_RC=$?
  rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run
  service lightdm start
  ### See /usr/share/doc/NVIDIA_GLX-1.0/README.txt

  if [ $NVIDIA_RC != 0 ]; then
    tail -n15 /var/log/nvidia-installer.log
    echo "FAIL: Execution of NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run RC=$NVIDIA_RC"
    exit $NVIDIA_RC
  fi

else # USE_DEB_METHOD
  ### Ref: https://www.pugetsystems.com/labs/hpc/The-Best-Way-To-Install-Ubuntu-16-04-with-NVIDIA-Drivers-and-CUDA-1097/
  add-apt-repository ppa:graphics-drivers/ppa
  apt-get install dkms synaptic build-essential
  apt-get update
  apt-get -y install nvidia-387
fi

  cat >> /etc/profile.d/nvidia.sh << NVIDIA_DRIVERS_INSTALLED
export NVIDIA_VERSION=$NVIDIA_VERSION
export NVIDIA_VER=$NVIDIA_VER
export NVIDIA_SUB=$NVIDIA_SUB
export PATH=/usr/lib/nvidia-\$NVIDIA_VER/bin:\$PATH
export LD_LIBRARY_PATH=/usr/lib/nvidia-\$NVIDIA_VER\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}
export NVIDIA_DRIVERS_INSTALLED=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_DRIVERS_INSTALLED

  pip install gpustat

  cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_SH
  chmod 0754 /etc/profile.d/nvidia.sh

  echo "Nvidia drivers have been installed."
  echo "After this reboot, install-nvidia will be complete."

  echo "Hit ctrl-C to abort the reboot."
  sleep 10
  reboot

fi