#!/bin/bash

apt-get -y install nvidia-cuda-dev libboost-all-dev
which cmake || /opt/mining/install/install-cmake || exit 1
[ -f /etc/profile.d/cuda.sh  ] || /opt/mining/install/install-cuda || exit 1
source /etc/profile.d/cuda.sh

pushd /opt
### Ref: https://github.com/nicehash/nheqminer/issues/341
### old- git clone https://github.com/nicehash/nheqminer || exit 1
git clone https://github.com/aayanl/nheqminer.git || exit 1

pushd nheqminer/cpu_xenoncat/asm_linux/
chmod +x fasm
sh assemble.sh

### bundeled fasm not compatible:
### delete/replace (inside nheqminer/cpu_xenoncat/asm_linux/ directory) with fasm binary compatible with your distro
# cd nheqminer/cpu_xenoncat/asm_linux/
# sh assemble.sh

popd
mkdir build ; pushd build
### Ref: https://github.com/nicehash/nheqminer/issues/341 (this problem fixed by aayanl)
### export BOOST_ROOT=/usr/lib/x86_64-linux-gnu
#set-in /etc/profile.d/cuda.sh: export CUDA_CUDART_LIBRARY=/usr/local/cuda-9.1/lib64
### Ref: https://github.com/nicehash/nheqminer/issues/228
cmake -DCUDA_CUDART_LIBRARY=CUDA_CUDART_LIBRARY ../nheqminer
### Ref: https://github.com/nicehash/nheqminer/issues/341 (this problem fixed by aayanl)
### touch ../nheqminer/cuda_djezo/device_functions_decls.h
make -j $(nproc)
cp -f nheqminer /usr/local/bin/
popd
rm -rf /opt/build
popd

### Ref: https://coinad.info/bwl-knowledge-base/equihash-zcash-mining/
### Also: https://www.nicehash.com/help/zcash-mining
## AMD GPU mining instructions
#./nheqminer -l equihash.[LOCATION].nicehash.com:3357 -u [YOUR-BTC-ADDRESS.WORKER-NAME] -t 0 -od [AMD GPU OpenCL devices 0 1 ..]
## NVIDIA GPU mining instructions
#nheqminer -l equihash.[LOCATION].nicehash.com:3357 -u [YOUR-BTC-ADDRESS.WORKER-NAME] -t 0 -cd [NVIDIA GPU CUDA devices 0 1 ..]
#[
#nheqminer -l us-east.equihash-hub.miningpoolhub.com:20570 -u albokiadt.ZEC-nh-miner -p x -t 0 -od 0 1 2 3
#nheqminer -l us.zclmine.pro:9009 -u YOUR_ZCL_T-ADDR.ZCL-miner -p x 
#ssl://us.zclmine.pro:9999

cat >> /etc/profile.d/nheqminer.sh << NHEQMINER_SH
export INSTALL_NHEQMINER_DATE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NHEQMINER_SH
