#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

#=================== nVidia, claymore dual gpu miner ===============
### REF: https://steemit.com/ethereum/@virtualcoin/ethereum-claymore-dual-ethereum-gpu-miner-for-linux-geforce-gtx
### Ref: https://www.bminer.me/references/

ETHDCRMINER_VERSION=10.0

mkdir /opt/ethdcrminer64 ; chown $MINERS_USER /opt/ethdcrminer64
pushd /opt/ethdcrminer64 >/dev/null
  wget https://github.com/nanopool/Claymore-Dual-Miner/releases/download/v${ETHDCRMINER_VERSION}/Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v${ETHDCRMINER_VERSION}.-.LINUX.tar.gz
  tar -xzf Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v${ETHDCRMINER_VERSION}.-.LINUX.tar.gz
  rm Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v${ETHDCRMINER_VERSION}.-.LINUX.tar.gz
  echo "USAGE: cd /opt/ethdcrminer64 ; ./ethdcrminer64 [ options ... ]"
popd >/dev/null

cat >> /etc/profile.d/ethdcrminer64.sh << ETHDCRMINER64_SH
export INSTALL_ETHDCRMINER64_DATE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
ETHDCRMINER64_SH


# sudo journalctl -f
