#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

### See: https://github.com/sgminer-dev/sgminer/blob/master/doc/configuration.md

apt-get -y install libcurl4-openssl-dev pkg-config libtool libncurses5-dev
pushd /opt

git clone https://github.com/nicehash/sgminer.git
cd sgminer

git submodule init
git submodule update
autoreconf -i
CFLAGS="-O2 -Wall -march=native -std=gnu99" ./configure --without-curses
## There is one coding error; just change the 'TRUE' to 'true' in sgminer.c:811
sed -i.bak 's/pool->backup = TRUE;/pool->backup = true;/' sgminer.c
make
make install

cat >> /etc/profile.d/sgminer.sh << SGMINER_SH
export INSTALL_SGMINER_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
SGMINER_SH
source /etc/profile.d/sgminer.sh

sgminer --version
#> sgminer 5.6.1-nicehash

popd
