#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 must be run as root."
		sudo -H $0 $*
		exit $?
	fi

# Grab the rig-tag
[ -z "$HOSTNAME" ] && HOSTNAME=$(cat /etc/hostname)
r_tag=$(echo $HOSTNAME|sed 's/rig-//')
RIG_TAG=${1:-$r_tag}

# Create miners' user account
MINERS_USER=$2
if [ -z "$MINERS_USER" ]; then
  echo -n 'MINERS_USER account: '
  read MINERS_USER
  echo
fi
MINERS_PSW=$3
while [ -z "$MINERS_PSW" ]; do
  echo -n "$MINERS_USER password: "
  read -s MINERS_PSW_FIRST
  echo
  echo -n "$MINERS_USER password, again: "
  read -s MINERS_PSW_AGAIN
  echo
  if [ "$MINERS_PSW_AGAIN" = "$MINERS_PSW_FIRST" ]; then
    MINERS_PSW=$MINERS_PSW_FIRST
    break
  else
    echo "Passwords do not match."
  fi
done
MINING_ROOT=${MINING_ROOT:-/opt/mining}

usermod -a -G sudo -G staff -G root $MINERS_USER

cat  > /etc/sudoers.d/miners << ETC_SUDOERS
Defaults env_keep+="DISPLAY XAUTHORITY"
$MINERS_USER ALL=(ALL) NOPASSWD: ALL
ETC_SUDOERS
chmod 0440 /etc/sudoers.d/miners

[ ! -d /home/$MINERS_USER/.ssh ]&& mkdir /home/$MINERS_USER/.ssh && chmod 0700 /home/$MINERS_USER/.ssh
echo $MINERS_PSW > /home/$MINERS_USER/.ssh/miners_user.psw
chown $MINERS_USER:$MINERS_USER /home/$MINERS_USER/.ssh/miners_user.psw
chmod 0600 /home/$MINERS_USER/.ssh/miners_user.psw


### Ref: https://www.cyberciti.biz/python-tutorials/linux-tutorial-install-ansible-configuration-management-and-it-automation-tool/
apt-get -y install software-properties-common
apt-add-repository -y ppa:ansible/ansible
apt-get update
apt-get -y install ansible

HOSTNAME=rig-$RIG_TAG
hostname $HOSTNAME
echo $HOSTNAME > /etc/hostname
cat >> /etc/ansible/hosts << ANSIBLE_MINERS

[miners]
# Since this section is also read by miners.py for some of its configuration, this hosts
#   file's format is somewhat limited, to "<IP_ADDR> hostname=<hostname> platform=<plat>"
`hostname -I` hostname=$HOSTNAME platform=$PLATFORM

ANSIBLE_MINERS
sed -i.bak 's/#host_key_checking = False/host_key_checking = False/' /etc/ansible/ansible.cfg

usermod -a -G sudo  $MINERS_USER
usermod -a -G staff $MINERS_USER

cat  >> /etc/sudoers << ETC_SUDOERS
Defaults env_keep+="DISPLAY"
$MINERS_USER ALL=(ALL) NOPASSWD: ALL
ETC_SUDOERS

### Great post at https://zxq9.com/archives/795
cat >> /etc/environment << ETC_ENVIRONMENT
MINERS_USER=${MINERS_USER}
RIG_TAG=$RIG_TAG
MINING_ROOT=$MINING_ROOT
XAUTHORITY=/home/$MINERS_USER/.Xauthority
NO_AT_BRIDGE=1
ANSIBLE_HOST_KEY_CHECKING=False
INSTALL_DATE_MINERS=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NO_AT_BRIDGE=1
ANSIBLE_HOST_KEY_CHECKING=False
ETC_ENVIRONMENT
source /etc/environment

### Turn off PCI ASPM (active state power management)
### Ref: https://askubuntu.com/questions/68372/how-do-i-add-pcie-aspm-force-to-my-boot-options
sed -i.bak 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=off"/' /etc/default/grub
update-grub

### TODO: Is there really a 20% hit on hashrate if upgrade Ubuntu after Jan 19 2018?!
### Ref: http://www.cryptobadger.com/2017/05/build-ethereum-mining-rig-faq/#kernal_update
### Ref: http://ask.xmodulo.com/disable-automatic-updates-ubuntu.html
echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/10periodic 

# Make and configure some initial directories
MINERS_FOLDERS='/opt/mining /var/mining /var/log/mining /var/run/miners /var/local/persist /opt/Downloads /etc/mining /etc/ansible'
mkdir -p $MINERS_FOLDERS 2>/dev/null
chown -R ${MINERS_USER} $MINERS_FOLDERS
# Make ~/.ssh folders in root and $MINERS_USER accounts
mkdir -p ~/.ssh/config.d >/dev/null /home/${MINERS_USER}/.ssh/config.d >/dev/null
chmod 0700 ~/.ssh/config.d /home/${MINERS_USER}/.ssh/config.d
chown -R $MINERS_USER:$MINERS_USER /home/${MINERS_USER}/.ssh

echo "Basic OS, accounts, etc., for mining have been prepared."
echo "A reboot is highly recommended at this point."

echo "Hit ctrl-C to abort the reboot."
sleep 10
reboot
