#!/bin/bash

if [[ $EUID -ne 0 ]]
then
    printf "%s\n" "This script must be run as root" 
    exit 1
fi
pushd /opt

NVIDIA_VERSION=${1:390.59}
NVIDIA_VER_PTC=(${NVIDIA_VERSION//./ })
NVIDIA_VER=${NVIDIA_VER_PTC[0]}
NVIDIA_PATCH=${NVIDIA_VER_PTC[1]}

cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_VERSION=$NVIDIA_VERSION
export NVIDIA_VER=$NVIDIA_VER
export NVIDIA_PATCH=$NVIDIA_PATCH
export PATH=/usr/lib/nvidia-\$NVIDIA_VER/bin\${PATH:+:\$PATH}
export LD_LIBRARY_PATH=/usr/lib/nvidia-\$NVIDIA_VER${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}
NVIDIA_SH
source /etc/profile.d/nvidia.sh

### Ref: https://github.com/pearsonlab/pearsonlab.github.io/wiki/Things-to-know-when-installing-NVIDIA-drivers
apt-get -y remove --purge nvidia* nouveau* && apt-get -y autoremove
cat > /etc/modprobe.d/disable-nouveau.conf << EOT
blacklist nouveau
options nouveau modeset=0
blacklist lbm-nouveau
blacklist nvidia-173
blacklist nvidia-96
blacklist nvidia-current
blacklist nvidia-173-updates
blacklist nvidia-96-updates
alias nvidia nvidia_current_updates
alias nouveau off
alias lbm-nouveau off
EOT
update-initramfs -u

cat > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf << NOUVEAU_OFF
blacklist nouveau
options nouveau modeset=0
NOUVEAU_OFF

[ -n "$REBOOT_WHEN_NEEDED" ] && reboot || source /etc/profile.d/nvidia.sh

cd /opt/Downloads/
wget https://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VER}.${NVIDIA_PATCH}/NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
### Question: When will we ever need X server?
### Answer: nvidia-settings is too stupid to talk directly to its own GPUs and has to use X-server to do that for it.
service lightdm stop
sh NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
service lightdm start
### See /usr/share/doc/NVIDIA_GLX-1.0/README.txt

## gpustat works only for Nvidia GPUs
pip install gpustat
gpustat --no-color --show-cmd --show-power --json

### TEST
cat /proc/driver/nvidia/version
lsmod | grep nvidia
nvidia-smi -L
lspci|grep VGA

[ -n "$VERBOSE" ] && nvidia-smi -a 


cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_SH
chmod 0754 /etc/profile.d/nvidia.sh
