#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

#=================== Claymore Neoscrypt gpu miner ===============
### Ref: https://bitcointalk.org/index.php?topic=3012600.0
### FIXME: NO LINUX SUPPORT


[ ! -f /opt/Downloads/Claymore\'s\ NeoScrypt\ AMD\ GPU\ Miner\ v1.0.zip ] && \
    echo "You must manually fetch '"Claymore's NeoScrypt AMD GPU Miner v1.0.zip"' into /opt/Downloads from https://mega.nz/#F!WthSUArb!00pET54lyIF1386tOGs1BQ" && exit 1
echo FIXME: NO LINUX SUPPORT ; exit 1 

mkdir /opt/zecminer64 2>/dev/null ; chown $MINERS_USER /opt/zecminer64
pushd /opt/zecminer64
  tar -xzf /opt/Downloads/Claymore\'s\ ZCash\ AMD\ GPU\ Miner\ v${ZECMINER64_VERSION}\ -\ LINUX.tar.gz
  mv Claymore\'s\ ZCash\ AMD\ GPU\ Miner\ v${ZECMINER64_VERSION}\ -\ LINUX/* ./
  rm -r Claymore\'s\ ZCash\ AMD\ GPU\ Miner\ v${ZECMINER64_VERSION}\ -\ LINUX*
  echo "USAGE: cd /opt/zecminer64 ; ./zecminer64 [ options ... ]"
popd

cat >> /etc/profile.d/ethdcrminer64.sh << ZECMINER64_SH
export INSTALL_ZECMINER64_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
ZECMINER64_SH
