#!/bin/bash

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 requires elevated privileges."
		sudo $0 $*
		exit;
	fi

RIG_TAG=${1:-BORG-B}
[ -z "$CREATE_DATE_MINERS" ] && /opt/mining/install/install--ME-first albokiadt $RIG_TAG && source /etc/environment

### Ref: Interesting recipes, all languages https://github.com/ActiveState/code/tree/master/recipes
### TODO Connect To Wifi From The Linux Command Line
###      Ref: https://linuxconfig.org/connect-to-wifi-from-the-linux-command-line

pushd /opt/mining/install/
### TODO: FIXME: automate this?
### MANUALLY copy GlennWood/mining/install/install-* into /opt/mining/install/
### OR, JUST copy GlennWood/mining/install/install-samba and use it ...
chmod 0754 /opt/mining/install/install-*
grep 'path = /opt/mining' /etc/samba/smb.conf >/dev/null 2>&1 || /opt/mining/install/install-samba $RIG_TAG
### Now we can SAMBA copy GlennWood/mining/install/ into /opt/mining/install/
chmod 0754 /opt/mining/install/install-*
/opt/mining/install/install-python

### Get miners python scripts from git:GlennWood/miners
chmod 0754 /opt/mining/*.py /opt/mining/*/*.py
ln -s /opt/mining/miners.py  /usr/local/bin/miners
ln -s /opt/mining/monitor.py /usr/local/bin/monitor-miners
#ln -s /opt/mining/stratum.py /usr/local/bin/stratum

[ -n "$INSTALL_WIFI" ] && /opt/mining/install/install-wifi $WIFI_SID $WIFI_PSW


# For AMD GPUs
PLATFORM=${PLATFORM:-BTH}
if [ "$PLATFORM" = "AMD" ] || [ "$PLATFORM" = "BTH" ]; then
  /opt/mining/install/install-amd-pro
  /opt/mining/install/install-opencl
  # Mining clients that work with AMD only
  /opt/mining/install/install-ethdcrminer64
  /opt/mining/install/install-gatelessgate
  /opt/mining/install/install-optiminer-zcash
  /opt/mining/install/install-sgminer
  /opt/mining/install/install-sgminer-phi
  /opt/mining/install/install-zecminer64
fi

# For Nvidia GPUs
if [ "$PLATFORM" = "NVI" ] || ["$PLATFORM" = "BTH" ]; then
  # For Nvidia GPUs - these are difficult to script, so manual operation is required
  /opt/mining/install/install-nvidia
  /opt/mining/install/install-cuda
    # or ./install-nvidia-and-cuda (or not; this is scripted, but hazardous if it goes wrong)
  # Mining clients that work with NVI only
  /opt/mining/install/install-bminer
  /opt/mining/install/install-ccminer-KlausT
  /opt/mining/install/install-dstm
  /opt/mining/install/install-ethminer
  /opt/mining/install/install-ewbf
  /opt/mining/install/install-nheqminer
  /opt/mining/install/install-suprminer
fi

### Mining clients that work with both AMD and NVI
###/opt/mining/install/install-eth-proxy
/opt/mining/install/install-ngsminer

/opt/mining/install/install-optiminer-equihash

# TODO: works with AMD only, but requires CUDA (?)
#/opt/mining/install/install-ccminer

/opt/mining/install/install-monitor


reboot

### Clean up logs
cd/opt/mining/install/va/opt/mining/install/log
sudo su
> lastlog
> wtmp
> dpkg.log 
> kern.log
> syslog
exit
