#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi


### Ref: https://github.com/tpruvot/ccminer/blob/linux/INSTALL

apt-get -y install automake pkg-config libtool
apt-get -y install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential

### INSTALL instructions say must use GCC 5 (not 6 or 7)
if [ false ]; then 
  apt-get -y install gcc-5 g++-5
  update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
fi

pushd /opt
  git clone https://github.com/tpruvot/ccminer.git
  cd ccminer
  ./autogen.sh
  ./configure
  ./build.sh
popd



: echo <<'EOM'
### Ref: https://ruclip.com/video/XdWr9pB5p_Q/how-to-mine-vertcoin-on-linux-with-a-nvidia-gpu-ccminer.html
#'''
#Carcarlo Pravettoni Месяц назад +1
#I also found this comment in GitHub page of tpruvot ccminer:
#https://github.com/tpruvot/ccminer/pull/25
#"Delete the code that include header file device_functions_decls.h, which is useless for ccminer and is not supported by cuda9.1 any more. ccminer should not generate any NVVM IR or use libdevice.
#I remove '#include < device_functions_decl.h >' from equi/eqcuda.hpp, ccminer builds fine"
#'''
sed -i.bak 's|#include <device_functions_decls.h>|//#include <device_functions_decls.h>|' equi/eqcuda.hpp
sed -i.bak 's|sm_21,compute_20|sm_52,compute_52|g' Makefile.am
sed -i.bak 's|compute_20|compute_52|g' Makefile.am

### Ref: 

EOM
