#!/bin/bash

### Ref: http://www.nvidia.com/Download/index.aspx

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit $?
	fi

pushd /opt

[ -n "$INSTALL_NVIDIA_DONE" ] && echo "Nvidia drivers and support already installed $INSTALL_NVIDIA_DONE." && echo "To restart over from scratch, 'rm /etc/profile.d/nvidia.sh', logout, and retry." && exit 0

NVIDIA_VERSION=${1:-396.26}
NVIDIA_VER_PTC=(${NVIDIA_VERSION//./ })
NVIDIA_VER=${NVIDIA_VER_PTC[0]}
NVIDIA_SUB=${NVIDIA_VER_PTC[1]}

################################################################################
### Phase 0: Setup autostart ###################################################
[ -f /etc/profile.d/nvidia.sh ] && source /etc/profile.d/nvidia.sh
if [ -z "$INSTALL_NVIDIA" ]; then

cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA_STARTED=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_SH

fi
source /etc/profile.d/nvidia.sh

################################################################################
### Phase 1: Remove Nouveau ####################################################
echo "Removing and disabling nouveau"
  
### Ref: https://github.com/pearsonlab/pearsonlab.github.io/wiki/Things-to-know-when-installing-NVIDIA-drivers
  apt-get -y remove --purge nvidia* nouveau* && apt-get -y autoremove
  cat > /etc/modprobe.d/disable-nouveau.conf << DISABLE_NOUVEAU
blacklist nouveau
options nouveau modeset=0
blacklist lbm-nouveau
blacklist nvidia-173
blacklist nvidia-96
blacklist nvidia-current
blacklist nvidia-173-updates
blacklist nvidia-96-updates
alias nvidia nvidia_current_updates
alias nouveau off
alias lbm-nouveau off
DISABLE_NOUVEAU

  cat > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf << BLACKLIST_NOUVEAU
blacklist nouveau
options nouveau modeset=0
BLACKLIST_NOUVEAU

### TODO: Why update-initramfs if 'remove --purge' didn't do anything?
###    0 upgraded, 0 newly installed, 0 to remove and 156 not upgraded.
###    update-initramfs: Generating /boot/initrd.img-4.13.0-36-generic
  update-initramfs -u

  echo "NVIDIA_NOUVEAU_REMOVED="`date --utc +%Y-%m-%dT%H-%M-%SZ` >> /etc/profile.d/nvidia.sh
  echo "Nouveau has been removed and disabled."
  echo "After this reboot, install-nvidia can continue installation of Nvidia drivers."
  echo "  Your next step will be 'sudo /opt/mining/install/install-nvidia-2nd'."

  echo "Hit ctrl-C to abort the reboot."
  for cnt in {10..0}
  do
    echo -n -e "\rReboot in $cnt "
    sleep 1
  done
  echo -n -e   "\rRebooting ... "
  reboot
