#!/bin/bash

    if [[ $EUID -ne 0 ]]
    then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

# Create miners' user account
MINERS_USER=${1:-albokiadt}
[ -z "$HOSTNAME" ] && HOSTNAME=$(cat /etc/hostname)
r_tag=$(echo $HOSTNAME|sed 's/rig-//')
RIG_TAG=${2:-$r_tag}
echo MINERS_USER=$MINERS_USER RIG_TAG=$RIG_TAG

HOSTNAME=rig-$RIG_TAG
hostname $HOSTNAME
echo $HOSTNAME > /etc/hostname

usermod -a -G sudo $MINERS_USER

cat  >> /etc/sudoers << ETC_SUDOERS
Defaults env_keep+="DISPLAY"
$MINERS_USER ALL=(ALL) NOPASSWD: ALL
ETC_SUDOERS

# Make and configure some initial directories
mkdir -p /opt/mining/install /var/mining /var/log/mining /var/run/miners /opt/Downloads /etc/mining 2>/dev/null
chown -R ${MINERS_USER} /opt /var/mining /var/log/mining /var/run/miners /opt/Downloads /etc/mining

# Figure out if we have AMD graphic cards, Nvidia graphic cards, or both
HAS_AMD=$(lspci | grep VGA | grep AMD    >/dev/null && echo AMD)
HAS_NVI=$(lspci | grep VGA | grep NVIDIA >/dev/null && echo NVI)
[ -n "$HAS_AMD" ] && PLATFORM=$HAS_AMD
[ -n "$HAS_NVI" ] && PLATFORM=$HAS_NVI
[ -n "$HAS_AMD" ] && [ -n "$HAS_NVI" ] && PLATFORM=BTH

### Great post at https://zxq9.com/archives/795
cat >> /etc/environment << ETC_ENVIRONMENT
CREATE_DATE_MINERS=`date --utc +%Y-%m-%dT%H-%M-%SZ`
MINERS_USER=${MINERS_USER}
RIG_TAG=$RIG_TAG
PLATFORM=$PLATFORM
LOG_DIR=/var/log/mining
NO_AT_BRIDGE=1
ETC_ENVIRONMENT
source /etc/environment

#echo '. /etc/profile' >> /root/.bashrc
#echo '. /etc/profile' >> /home/${MINERS_USER}/.bashrc

### Turn off PCI ASPM (active state power management)
### Ref: https://askubuntu.com/questions/68372/how-do-i-add-pcie-aspm-force-to-my-boot-options
sed -i.bak 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash pcie_aspm=off"/' /etc/default/grub
update-grub

### TODO: Is there really a 20% hit on hashrate if upgrade Ubuntu after Jan 19 2018?!
### Ref: http://www.cryptobadger.com/2017/05/build-ethereum-mining-rig-faq/#kernal_update
### Ref: http://ask.xmodulo.com/disable-automatic-updates-ubuntu.html
echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/10periodic 

RAMDISK_SIZE=40M
mkdir -p /var/local/ramdisk
mount -t tmpfs -o size=${RAMDISK_SIZE} tmpfs /var/local/ramdisk
chown ${MINERS_USER} /var/local/ramdisk         
echo "none /var/local/ramdisk tmpfs nodev,nosuid,noexec,nodiratime,size=${RAMDISK_SIZE} 0 0" >> /etc/fstab
## Test
mount | grep /var/local/ramdisk

apt-get -y update ; apt-get -y dist-upgrade
apt-get -y autoremove ; apt-get -y autoclean

apt-get -y install openssh-server git autoconf curl selinux-utils expect lrzip
apt-get -y install libffi-dev libssl-dev python3-dev python3-pip

pip install --upgrade pip
pip install xlrd docopt requests
pip3 install bitshares
# For PyCryptScraper
apt-get -y install python-lxml
pip install -U marshmallow --pre

[ -n "$REBOOT_WHEN_NEEDED" ] && reboot || echo "A reboot is highly recommended at this point."
