#!/bin/bash

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 requires elevated privileges."
		sudo -H $0 $*
		exit;
	fi

### Ref: https://github.com/zawawawa/gatelessgate.git
### A newer fork exists, but only for Windows (in .Net/cs): https://github.com/zawawawa/GatelessGateSharp

apt-get -y install libcurl4-openssl-dev pkg-config libtool libncurses5-dev
pushd /opt

git clone https://github.com/zawawawa/gatelessgate.git
cd gatelessgate

git submodule init
git submodule update

cd Core
autoreconf -i
CFLAGS="-O2 -Wall -march=native -std=gnu99 -ggdb" ./configure --without-curses
make
make install

##echo 'export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH' > /etc/profile.d/sgminer.sh

gatelessgate --version
#> gatelessgate 0.1.3-pre6

echo "USAGE: gatelessgate --url stratum+tcp://equihash.usa.nicehash.com:3357 -u 346u4oMvACtZQK9RASzcgYoZwX4JaAd3Pi.EQUIHASH_miner -p x --gpu-platform 1"

popd
