#!/bin/bash

apt-get -y install automake autotools-dev pkg-config libtool libcurl4-openssl-dev libjansson-dev \
                   libssl-dev libcurl4-openssl-dev libssl-dev libjansson-dev build-essential

[ -f /etc/profile.d/cuda.sh ] || /opt/mining/install/install-cuda

pushd /opt
  git clone https://github.com/ocminer/suprminer.git
  cd suprminer
  ### The README says:
#  The recommended CUDA Toolkit version was the *6.5.19*, but some light algos could be
#  faster with the version 7.5 and 8.0 (like lbry, decred and skein).
  
### Ref: https://github.com/aria2/aria2/issues/120
### AUTOMAKE_OPTIONS or AM_INIT_AUTOMAKE([subdir-objects])
  ./autogen.sh
  ./configure
  ./build.sh
  ./ccminer --ndevs
  [ -n "$RUN_ALL_TESTS" ] && ./ccminer --algo=neoscrypt --benchmark

# [2018-02-11 05:13:04] Total: 4283.85 kH/s (four 1070s)

popd

cat >> /etc/profile.d/ccminer_klaust.sh << CCMINER_KLAUST_SH
export INSTALL_CCMINER_KLAUST_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
CCMINER_KLAUST_SH

# --ndevs
# --benchmark
