#!/bin/bash

### Ref: https://help.ubuntu.com/community/How%20to%20Create%20a%20Network%20Share%20Via%20Samba%20Via%20CLI%20%28Command-line%20interface/Linux%20Terminal%29%20-%20Uncomplicated%2C%20Simple%20and%20Brief%20Way%21

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit $?
	fi

apt-get update
apt-get -y install samba

samba_password=$(cat /home/$MINERS_USER/.ssh/miners_user.psw)
smbpasswd -s -a $MINING_USER << PSW
$samba_password
$samba_password
PSW

cat >> /etc/samba/smb.conf << SMB_CONF
[mining-${RIG_TAG}]
path = /opt/mining
available = yes
valid users = $MINING_USER
read only = no
browseable = yes
public = yes
writable = yes
SMB_CONF

service smbd restart
