#!/bin/bash

### Ref: http://www.nvidia.com/Download/index.aspx

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit $?
	fi

pushd /opt

[ -n "$INSTALL_NVIDIA_DONE" ] && echo "Nvidia drivers and support already installed $INSTALL_NVIDIA_DONE." && echo "To restart over from scratch, 'rm /etc/profile.d/nvidia.sh', logout, and retry." && exit 0

NVIDIA_VERSION=${1:-396.26}
NVIDIA_VER_PTC=(${NVIDIA_VERSION//./ })
NVIDIA_VER=${NVIDIA_VER_PTC[0]}
NVIDIA_SUB=${NVIDIA_VER_PTC[1]}

################################################################################
### Phase 2: Install Nvidia drivers ############################################
################################################################################
if [ -z "$NVIDIA_DRIVERS_INSTALLED" ]; then
  cd /opt/Downloads/
if [ -n "$USE_RUN_METHOD" ]; then # USE_RUN_METHOD
  [ -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
  wget https://us.download.nvidia.com/XFree86/Linux-x86_64/${NVIDIA_VER}.${NVIDIA_PATCH}/NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run
  [ ! -f NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_PATCH}.run ] && echo "Nvidia Drivers download failed!" && exit 1
  ### Question: When will we ever need X server?
  ### Answer: nvidia-settings is too stupid to talk directly to its own GPUs and has to use X-server to do that for it.
  service lightdm stop
  sh NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run --no-questions --disable-nouveau --ui=none --run-nvidia-xconfig
  NVIDIA_RC=$?
  rm NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run
  service lightdm start
  ### See /usr/share/doc/NVIDIA_GLX-1.0/README.txt

  if [ $NVIDIA_RC != 0 ]; then
    tail -n15 /var/log/nvidia-installer.log
    echo "FAIL: Execution of NVIDIA-Linux-x86_64-${NVIDIA_VER}.${NVIDIA_SUB}.run RC=$NVIDIA_RC"
    exit $NVIDIA_RC
  fi

else # USE_DEB_METHOD
  ### Ref: https://www.pugetsystems.com/labs/hpc/The-Best-Way-To-Install-Ubuntu-16-04-with-NVIDIA-Drivers-and-CUDA-1097/
  add-apt-repository -y ppa:graphics-drivers/ppa
  apt-get -y install dkms synaptic build-essential
  apt-get update
  apt-get -y install nvidia-$NVIDIA_VER
fi

  cat >> /etc/profile.d/nvidia.sh << NVIDIA_DRIVERS_INSTALLED
export NVIDIA_VERSION=$NVIDIA_VERSION
export NVIDIA_VER=$NVIDIA_VER
export NVIDIA_SUB=$NVIDIA_SUB
export PATH=/usr/lib/nvidia-\$NVIDIA_VER/bin:\$PATH
export LD_LIBRARY_PATH=/usr/lib/nvidia-\$NVIDIA_VER\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}
export NVIDIA_DRIVERS_INSTALLED=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_DRIVERS_INSTALLED

#  pip2 install gpustat
#  pip3 install gpustat
sudo pip install git+https://github.com/wookayin/gpustat.git@master
#sudo ln -s /usr/local/lib/python2.7/dist-packages/gpustat /usr/local/lib/python3.5/dist-packages/gpustat

  cat >> /etc/profile.d/nvidia.sh << NVIDIA_SH
export INSTALL_NVIDIA_DONE=`date --utc +%Y-%m-%dT%H-%M-%SZ`
NVIDIA_SH
  chmod 0754 /etc/profile.d/nvidia.sh

  echo "Nvidia drivers have been installed."
  echo "After this reboot, install-nvidia will be complete."

  echo "Hit ctrl-C to abort the reboot."
  sleep 10
  reboot

fi