#!/bin/bash

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit;
	fi

export MINING_ROOT=${MINING_ROOT:-/opt/mining}
RIG_TAG=${1:-RIG_TAG}
export MINERS_USER=${2:-albokiadt}

getent passwd $MINERS_USER || $MINING_ROOT/install/install-mining-user
[ -z "$INSTALL_DATE_MINERS" ] && $MINING_ROOT/install/install-1st $MINERS_USER $RIG_TAG && source /etc/environment
[ -z "$INSTALL_DATE_MINING" ] && $MINING_ROOT/install/install-2nd $MINERS_USER $RIG_TAG && source /etc/environment && source /etc/profile

### Ref: Interesting recipes, all languages https://github.com/ActiveState/code/tree/master/recipes
### TODO Connect To Wifi From The Linux Command Line
###      Ref: https://linuxconfig.org/connect-to-wifi-from-the-linux-command-line

[ -n "$INSTALL_WIFI" ] && $MINING_ROOT/install/install-wifi $WIFI_SID $WIFI_PSW

# For AMD GPUs
PLATFORM=${PLATFORM:-BTH}
if [ "$PLATFORM" = "AMD" ] || [ "$PLATFORM" = "BTH" ]; then
  $MINING_ROOT/install/install-amd-pro
  $MINING_ROOT/install/install-opencl
  $MINING_ROOT/install/install-GPUOpen-Tools
  # Mining clients that work with AMD only
  $MINING_ROOT/install/install-gatelessgate
  $MINING_ROOT/install/install-optiminer-zcash
  $MINING_ROOT/install/install-sgminer
  $MINING_ROOT/install/install-sgminer-phi
  $MINING_ROOT/install/install-zecminer64
fi

# For Nvidia GPUs
if [ "$PLATFORM" = "NVI" ] || ["$PLATFORM" = "BTH" ]; then
  # For Nvidia GPUs - these are difficult to script, so manual operation is required
  $MINING_ROOT/install/install-nvidia-and-cuda
  # Mining clients that work with NVI only
  $MINING_ROOT/install/install-bminer
  time $MINING_ROOT/install/install-ccminer
  time $MINING_ROOT/install/install-ccminer-KlausT
  $MINING_ROOT/install/install-dstm
  time $MINING_ROOT/install/install-ethminer
  $MINING_ROOT/install/install-ewbf
  time $MINING_ROOT/install/install-nheqminer
  time $MINING_ROOT/install/install-suprminer
fi

### Mining clients that work with both AMD and NVI
#$MINING_ROOT/install/install-eth-proxy
$MINING_ROOT/install/install-ethdcrminer64
$MINING_ROOT/install/install-ngsminer
$MINING_ROOT/install/install-optiminer-equihash
# TODO: works with AMD only, but requires CUDA (?)
#$MINING_ROOT/install/install-ccminer

$MINING_ROOT/install/install-monitor
