#!/bin/bash

  if [[ $EUID -ne 0 ]]
  then
		echo "$0 must be run as root."
		sudo $0 $*
		exit $?
	fi

if [ ! -f /usr/bin/systemback ]; then
  add-apt-repository -y ppa:nemh/systemback
  apt-get update
  apt-get -y install systemback unionfs-fuse genisoimage
fi

# AS USER albokiadt
sudo su $MINERS_USER << SYSTEMBACK
sudo systemback
SYSTEMBACK

if [ -n "$GENERATE_ISO_FILE" ]; then

## 1. Decompress the .sblive image:
mkdir sblive
tar -xf /home/systemback_live_2016-04-27.sblive -C sblive

## 2. Rename the syslinux to isolinux:
mv sblive/syslinux/syslinux.cfg sblive/syslinux/isolinux.cfg
mv sblive/syslinux sblive/isolinux

## 3. Generate the ISO file:
genisoimage -iso-level 3 -r -V sblive -cache-inodes -J -l -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table -c isolinux/boot.cat -o mining-20180520.iso sblive

add-apt-repository -y ppa:gezakovacs/ppa
apt-get update ; apt-get -y install unetbootin

mount -t vfat /dev/sda2 /media/usb -o uid=1000,gid=100,utf8,dmask=027,fmask=137

mount -t ntfs-3g /dev/sda2 /media/usb
fi

